RssFeeder/RssFeeder/Models/FeedItem.cs
using System;

namespace RssFeeder.Models
{
    public class FeedItem
    {
        public string Title { get; set; }
        public DateTime FeedDate { get; set; }
        public string Summary { get; set; }
        public string FeedUrl { get; set; }
        public string AuthorName { get; set; }
        public string AuthorEmail { get; set; }
    }
}

RssFeeder/RssFeeder/Controllers/FeedController.cs
using System.Web.Mvc;
using RssFeeder.Helpers;
using RssFeeder.Service;

namespace RssFeeder.Controllers
{
    public class FeedController : Controller
    {
        private readonly FeedService _feedService = new FeedService();

        //
        // GET: /RssFeeder/XmlFileFeed
        [HttpGet]
        public ActionResult XmlFileFeed(FeedType feedType, int noOfFeeds)
        {
            return new RssResult(_feedService.GenerateFeeds(noOfFeeds), feedType, false);
        }
        //
        // GET: /RssFeeder/XmlStreamFeed
        [HttpGet]
        public ActionResult XmlStreamFeed(FeedType feedType, int noOfFeeds)
        {
            return new RssActionResult(_feedService.GenerateFeeds(noOfFeeds), feedType);
        }
        [HttpGet]
        public ActionResult XmlXsltFeed(FeedType feedType, int noOfFeeds)
        {
            return new RssResultXslt(_feedService.GenerateFeeds(noOfFeeds), feedType);
        }
        public ActionResult XmlCssFeed(FeedType feedType, int noOfFeeds)
        {
            return new RssResult(_feedService.GenerateFeeds(noOfFeeds), feedType, true);
        }
    }
}
public enum FeedType
{
    Atom = 1,
    Rss = 2
}

RssFeeder/RssFeeder/Controllers/HomeController.cs
using System.Web.Mvc;

namespace RssFeeder.Controllers
{
    public class HomeController : Controller
    {
        //
        // GET: /Home/
        [HttpGet]
        public ActionResult Index()
        {
            return View();
        }
    }
}

RssFeeder/RssFeeder/Views/Home/Index.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
    <style type="text/css">
        body {
            font-family: sans-serif;
            background-color: #cccccc;
        }

        #wrapper {
            margin: 0 auto;
            width: 960px;
        }

        .table {
            display: table;
        }

        .row {
            display: table-row;
        }

        .cell {
            display: table-cell;
            width: 480px;
        }

        .title {
            font-size: 1em;
            text-align: center;
        }

        a {
            text-decoration: none;
            font-weight: bold;
        }

            a:hover {
                text-decoration: underline;
            }
    </style>
</head>
<body>
    <div id="wrapper">
        <div class="title">
            <h1>Simple Rss Feed using ASP.Net MVC and WCF Syndication Class.</h1>
        </div>
        <div class="table">
            <div class="row">
                <div class="cell">
                    <fieldset>
                        <legend>Load Feed as Xml Stream</legend>
                        <div>
                            @Html.ActionLink("RssFeed", "XmlStreamFeed", "Feed", new { feedType = @FeedType.Rss, noOfFeeds = 10 }, null)<br />
                            @Html.ActionLink("AtomFeed", "XmlStreamFeed", "Feed", new { feedType = @FeedType.Atom, noOfFeeds = 10 }, null)
                        </div>
                    </fieldset>
                </div>
                <div class="cell">
                    <fieldset>
                        <legend>Load Feed as Xml File</legend>
                        <div>
                            @Html.ActionLink("RssFeed", "XmlFileFeed", "Feed", new { feedType = @FeedType.Rss, noOfFeeds = 10 }, null)<br />
                            @Html.ActionLink("AtomFeed", "XmlFileFeed", "Feed", new { feedType = @FeedType.Atom, noOfFeeds = 10 }, null)
                        </div>
                    </fieldset>
                </div>
            </div>
            <div class="row">
                <div class="cell">
                    <fieldset>
                        <legend>Load Rss Feed with XSLT styles.</legend>
                        <div>
                            @Html.ActionLink("RssFeedWithXSLTStyles", "XmlXsltFeed", "Feed", new { feedType = @FeedType.Rss, noOfFeeds = 10 }, null)<br />
                        </div>
                    </fieldset>
                </div>
                <div class="cell">
                    <fieldset>
                        <legend>Load Rss Feed with CSS styles.</legend>
                        <div>
                            @Html.ActionLink("RssFeedWithCSSStyles", "XmlCssFeed", "Feed", new { feedType = @FeedType.Rss, noOfFeeds = 10 }, null)<br />
                        </div>
                    </fieldset>
                </div>
            </div>
        </div>

    </div>
</body>
</html>